### ISSUE TITLE
Server version spawn

### ISSUE THREAD

**Issue by AKTheKnight** [SnowShock35/Obscurity#70]
I downloaded the server pack to test and see if I could host it on my box, but the server spawn behaves differently from single-player... makes it almost unplayable. In the single-player a spawn is constructed and I start on top of a tower with lighting and some protection against mobs and darkness. On the server I'm spawned underground upon my first time logging in and forced to suffocate to death, and then spawn again high up in the air and fall to where I originally suffocated. The area has no lighting or protection, and I must quickly collect my dropped items on the ground before running away from the horde of mobs now intent on ending me. It's difficult to grab my bearings and not possible to take a moment to even read up on the quest book or even make a shelter.

I've reproduced this same exact problem about five times, and I can't figure out why it's not constructing spawn the same as the single-player world.

**Comment by AKTheKnight** [comment]
Issue fixed if a singleplayer world is copied over instead

**Comment by SnowShock35** [comment]
should be fixed for 1.1.12, if not well you'll get a working one with new map version ;)

**Comment by SnowShock35** [comment]
Assumed Fixed

**Comment by SnowShock35** [comment]
Not actually fixed woops

**Comment by SnowShock35** [comment]
Fixed now!

**Comment by AKTheKnight** [comment]
#BlameSnow

**Comment by SnowShock35** [comment]
\

**Comment by SnowShock35** [comment]
Fixed in 1.1.15_Beta

**Comment by BrzlMan** [comment]
hate to say this, but I am still having issues with the spawn in a server. no matter what I try, I spawn in the overworld somewhere. I have tried copying over a single player worlds, letting worlds generate on their own, with and without the perfectspawn file, but to no avail.

**Comment by SnowShock35** [comment]
Hai @BrzlMan 

Sorry for the delayed reply.

I'm still uncertain as to why this happens with some peoples setups :confused: I hope the 2.0.0 update will fix this but other than that I have no idea what else to suggest. 

Sorry about this,
SnowShock.

**Comment by SnowShock35** [comment]
@AKTheKnight Fix this for me AK ;)

**Comment by AKTheKnight** [comment]
haha yeah what? I would suggest adding the single player map to the server version. See what happens

**Comment by SnowShock35** [comment]
Me testing it doesn't work because I built the map so my name is already in the level data file. could u try the server version again?

**Comment by AKTheKnight** [comment]
It'll be a 30 min download (probs more) But I'll have this checked by tomorrow

**Comment by SnowShock35** [comment]
@AKTheKnight K Thanks bud

**Comment by AKTheKnight** [comment]
uhh. Seems like the server download from ftb is in a weird format? Having issues. I'll check tomorrow

**Comment by SnowShock35** [comment]
@AKTheKnight You sure? :confused:

**Comment by SnowShock35** [comment]
@AKTheKnight Use this DL link http://ftb.cursecdn.com/FTB2/modpacks/Obscurity/1_1_16/ObscurityServer.zip
